//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnigramsNotebook.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotebookEntities : DbContext
    {
        public NotebookEntities()
            : base("name=NotebookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NBCategory> NBCategories { get; set; }
        public virtual DbSet<NBCharacter> NBCharacters { get; set; }
        public virtual DbSet<NBCreature> NBCreatures { get; set; }
        public virtual DbSet<NBGroup> NBGroups { get; set; }
        public virtual DbSet<NBItem> NBItems { get; set; }
        public virtual DbSet<NBLanguage> NBLanguages { get; set; }
        public virtual DbSet<NBLocation> NBLocations { get; set; }
        public virtual DbSet<NBMagic> NBMagics { get; set; }
        public virtual DbSet<NBOther> NBOthers { get; set; }
        public virtual DbSet<NBPlant> NBPlants { get; set; }
        public virtual DbSet<NBProject> NBProjects { get; set; }
        public virtual DbSet<NBRace> NBRaces { get; set; }
        public virtual DbSet<NBRegion> NBRegions { get; set; }
        public virtual DbSet<NBReligion> NBReligions { get; set; }
        public virtual DbSet<NBScene> NBScenes { get; set; }
        public virtual DbSet<NBUniverse> NBUniverses { get; set; }
        public virtual DbSet<NBPrompt> NBPrompts { get; set; }
        public virtual DbSet<NBResource> NBResources { get; set; }
        public virtual DbSet<NBAssociation> NBAssociations { get; set; }
        public virtual DbSet<NBImage> NBImages { get; set; }
        public virtual DbSet<NBNote> NBNotes { get; set; }
        public virtual DbSet<NBChanges_View> NBChanges_View { get; set; }
        public virtual DbSet<NBSearch_View> NBSearch_View { get; set; }
        public virtual DbSet<NBGovernment> NBGovernments { get; set; }
        public virtual DbSet<NBHistory> NBHistories { get; set; }
    }
}
