//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnigramsNotebook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NBPrompt
    {
        public int NBPromptId { get; set; }
        public int NBCategoryId { get; set; }
        public string Text { get; set; }
        public string Source { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual NBCategory NBCategory { get; set; }
    }
}
