//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnigramsNotebook.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NBSearch_View
    {
        public long NBSearchId { get; set; }
        public string CategoryName { get; set; }
        public int ObjectId { get; set; }
        public int NBProjectId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string IconName { get; set; }
        public string Color { get; set; }
        public bool IsActive { get; set; }
    }
}
